---
title: "Assignment 1 Task 2"
author: "Grace Kumaishi"
date: "1/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

library(tidyverse)
library(janitor)
library(palmerpenguins)
library(here)

# For PCA:
library(ggfortify)

# For ggplot customization:
library(readxl)
library(gghighlight)
library(lubridate)
library(plotly)
```

### Introduction:

### Principal components analysis:

```{r}
# Read in data:

world_env_vars <- read_csv(here("data", "world_env_vars.csv")) %>% 
  clean_names() 
```

```{r}
# Create PCA dataset:

world_env_pca <- world_env_vars %>% 
  select_if(is.numeric) %>% 
  select(-c(ends_with("_quart"))) %>% # remove any column ending in '_quart'
  select(-c(ends_with("_month"))) %>% # remove any column ending in '_month'
  select(-c("accessibility_to_cities", "aspect")) %>% 
  drop_na() %>% 
  scale() %>% 
  prcomp()

world_env_pca$rotation

world_env_complete <- world_env_vars %>% 
  drop_na()
```

```{r}
# Generate PCA plot:

autoplot(world_env_pca,
         data = world_env_complete,
         colour = "country",
         loadings = TRUE, 
         loadings.colour = "gray50",
         loadings.label = TRUE,
         loadings.label.colour = "black",
         loadings.label.vjust = 1,
         show.legend = FALSE)+
  theme_minimal() +
  theme(legend.position = "none") # remove legend
```


### Summary:
- Points closer together represent countries that....




