---
title: "Assignment 1 Task 1"
author: "Grace Kumaishi"
date: "1/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
library(tidyverse)
library(here)
library(janitor)
library(readxl)
library(lubridate)
library(patchwork)
```

### 1) Read in the data

```{r}
amphibians <- read_excel(here("data", "sierra_amphibians.xlsx")) %>% 
  mutate(across(where(is.character), tolower)) # convert all cells to lower case
```
### 2) Graph #1

#### a) Data wrangling:

```{r}
ramu <- amphibians %>% 
  select("survey_date", "amphibian_species", "amphibian_life_stage", "amphibian_number") %>% 
  filter(amphibian_life_stage != "eggmass") %>% # select all life stages but eggmass
  filter(amphibian_species == "ramu") %>% 
  mutate(year = year(survey_date)) %>% # create new column for 'year'
  group_by(year, amphibian_life_stage) %>% # group by both year and amphibian life stage in preparation for summing all counts
  summarize(individual_count = sum(amphibian_number, na.rm = TRUE))
```

#### b) Create graph using ggplot:

```{r}
graph_1 <- ggplot(data = ramu, aes(x = year, y = individual_count)) +
  geom_col(aes(fill = amphibian_life_stage)) +
  scale_fill_manual(values = c("coral", "goldenrod2", "cyan4")) +
  facet_wrap(~amphibian_life_stage) +
  labs(x = "Year",
       y = "Number of Individuals",
       title = "Mountain yellow-legged frog count across life stages and location",
       fill = "Life Stage") +
  theme(plot.title = element_text(hjust = 0)) +
  theme_minimal()
```

### 3) Graph #2

#### a) Data wrangling:

```{r}
amphibians$lake_id <- as.character(as.numeric(amphibians$lake_id)) # convert from numeric to character class

ramu_lakes <- amphibians %>% 
  select("lake_id", "amphibian_species", "amphibian_life_stage", "amphibian_number") %>% 
  filter(amphibian_species == "ramu") %>% 
  filter(amphibian_life_stage == c("adult", "subadult")) %>% 
  group_by(lake_id) %>% 
  summarize(ramu_count = sum(amphibian_number)) %>% 
  mutate(lake_id = fct_reorder(lake_id, ramu_count)) %>% 
  slice_max(ramu_count, n = 5)
```

#### b) Create graph using ggplot:

```{r}
graph_2 <- ggplot(data = ramu_lakes, aes(x = ramu_count, y = lake_id)) +
  geom_col(fill = "steelblue") +
  labs(x = "Count (n)",
       y = "Lake identification number") +
  theme_minimal()
```

### 4) Combine graphs 1 & 2 

```{r, fig.align = "center"}
# Combine graphs using patchwork
graph_3 <- graph_1/graph_2

graph_3
```
**Figure 1:**

